# Use a minimal Python image
FROM python:3.12

# Set working directory inside container
WORKDIR /app


# Copy your code and requirements
COPY weaviate_k8_test.py /app/
COPY requirements.txt /app/
# COPY .env /app/ #for DEVELOPMENT ONLY, not needed in production


# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Run your Python script when container starts
# CMD ["python", "weaviate_k8_test.py"]

CMD ["uvicorn", "weaviate_k8_web:app", "--host", "0.0.0.0", "--port", "8000"]