# weaviate-cloud-deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: weaviate-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-app
  namespace: weaviate-namespace
  labels:
    app: weaviate-app
    cluster: weaviate-cluster-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weaviate-app
  template:
    metadata:
      labels:
        app: weaviate-app
        cluster: weaviate-cluster-b
    spec:
      containers:
      - name: weaviate-app
        image: kiitangnk/weaviate-search-app:linux
        ports:
        - containerPort: 8000
        # Environment variables for Weaviate Cloud Service and application configuration
        env:
        #cluster environment variables
        - name: CLUSTER_NAME
          value: "weaviate-cluster-b"
        # Weaviate Cloud Service configuration
        - name: WEAVIATE_CLOUD_ENABLED
          value: "true"
        - name: WEAVIATE_URL
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: WEAVIATE_URL
        - name: WEAVIATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: WEAVIATE_API_KEY
        # Application configuration
        - name: QUERY_DEFAULTS_LIMIT
          value: "20"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "text2vec-openai"
        - name: ENABLE_MODULES
          value: "text2vec-openai,text2vec-cohere,generative-openai"
        # OpenAI API Key (if using OpenAI modules)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: OPENAI_API_KEY
              optional: true
        # Cohere API Key (if using Cohere modules)
        - name: COHERE_API_KEY
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: COHERE_API_KEY
              optional: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-app-service
  namespace: weaviate-namespace
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: weaviate-app
  type: LoadBalancer